-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE "Bill"."Bill"
(
    id bigint NOT NULL,
    pay_date date NOT NULL,
    title character(200) NOT NULL,
    value character(1) NOT NULL,
    "isPay" boolean NOT NULL,
    email character(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.bill
(
    id integer NOT NULL,
    is_pay boolean,
    pay_date character varying(255),
    title character varying(255),
    value character varying(255),
    email character varying(255),
    PRIMARY KEY (id)
);
END;